# Generated by Django 3.2.4 on 2021-09-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alternate_submit_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
