# Generated by Django 3.2.6 on 2021-09-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210907_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_protein_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_shoe_sizes',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
